### ISSUE TITLE
Cannot read property 'hasPermission' of undefined

### ISSUE THREAD

**Issue by alex0754** [breftejk/Discord.js-Web-Dashboard#1]
Hello, there is an error in your code that makes your dashboard unusable

File : app.js
Line : 60
Code : `if (!bot.guilds.cache.get(req.params.id).members.cache.get(req.session.user.id).hasPermission('MANAGE_GUILD'))`
Error : Cannot read property 'hasPermission' of undefined

**Comment by breftejk** [comment]
Hello,
I apologize in advance for any delays. I checked it and it is because of the change and Discord's API and only verified bots have access to this feature. Weird. I will try to find another solution to this problem.
Greetings

**Comment by breftejk** [comment]
Fixed.
