### ISSUE TITLE
[idea]

### ISSUE THREAD

**Issue by legendary0001** [breftejk/Discord.js-Web-Dashboard#18]
Option for More than one table in commands page

**Comment by breftejk** [comment]
What do you mean?

**Comment by legendary0001** [comment]
In commands page we should have ability to create more than one table [just like settings page]
![IMG_20210901_000221](https://user-images.githubusercontent.com/76104734/131557224-5efcb2d3-97d1-43dd-8f18-1c98775dfe72.jpg)

**Comment by legendary0001** [comment]
😁

**Comment by legendary0001** [comment]
☠️

**Comment by legendary0001** [comment]
Hello?

**Comment by breftejk** [comment]
I'll think about it...

**Comment by breftejk** [comment]
Closed for **themes-related stuff**.

Please open an issue on the theme github page: https://github.com/breftejk/DBD-capriham-theme/issues
