### ISSUE TITLE
How do I Fetch all text channels from a Guild?

### ISSUE THREAD

**Issue by BetaDv** [breftejk/Discord.js-Web-Dashboard#2]
How do I fetch this and make a list with it?

**Comment by breftejk** [comment]
Hello!
With what?

**Comment by breftejk** [comment]
Oh yeah, I see
text channels
You can do it via discord client, with discord.js:

<DiscordClient>.guilds.cache.get(guildID).channels.cache => channels list from cache

then you can use forEach with it :D

**Comment by breftejk** [comment]
Hi,
According to the answer to the question, I close the topic for now. If there are any additional problems or questions, please open another one.
I also apologize for any delays.
