### ISSUE TITLE
Multiple channels/roles selection bug

### ISSUE THREAD

**Issue by justapieop** [breftejk/Discord.js-Web-Dashboard#28]
Multiple channels/roles selection are still required even when the required parameter is set to false
![image](https://user-images.githubusercontent.com/57786194/142367306-f7787b2c-8cc3-4683-9589-1a97712989b0.png)
![image](https://user-images.githubusercontent.com/57786194/142367375-3eefedad-7742-43e4-b879-09ca2316b5c5.png)

**Comment by breftejk** [comment]
An empty value will be added today.

**Comment by Default-01** [comment]
my pull request will fix that :)

**Comment by breftejk** [comment]
Use discord-dashboard v1.4.5 update.

**Comment by justapieop** [comment]
The bug hasn't been fixed

**Comment by breftejk** [comment]
You have not an empty option :D
