### ISSUE TITLE
TypeError: DBD.useLicense is not a function

### ISSUE THREAD

**Issue by FunkiCraft** [breftejk/Discord.js-Web-Dashboard#41]
I get the error: 

await DBD.useLicense('XXXXXXXXXXXXXXXXXXXXXXXX');
          ^

TypeError: DBD.useLicense is not a function

**Comment by breftejk** [comment]
Hello,
Thank you for your report.

Which version of the discord-dashboard are you using?

Greetings and waiting for reply,
breftejk

**Comment by FunkiCraft** [comment]
i use the Dark Dashboard Version 1.5.21

**Comment by breftejk** [comment]
You need to update it to v2.*

**Comment by FunkiCraft** [comment]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for dbd-dark-dashboard@2.0.31
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

**Comment by breftejk** [comment]
discord-dashboard* not dbd-dark-dashboard

**Comment by FunkiCraft** [comment]
oh thanks now its working sorry i am so stupid
